---
kind: pipeline
type: docker
name: default

trigger:
  event:
    - push
    - custom

steps:
  - name: lint shell
    image: koalaman/shellcheck-alpine:latest
    commands:
      - apk update
      - apk add bash make
      - make lint
